---
version: "3.3"

services:
  postgres_db-web:
    container_name: contoso_pets-db-web
    restart: always
    image: postgres:13.3-alpine
    environment:
      - POSTGRES_DB=contoso_pets
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  webapp:
    container_name: contoso_pets-webapp
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - postgres_db-web
    ports:
      - 3000:80

  nginx:
    container_name: contoso_pets-proxy
    image: nginx:1.20-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - webapp
