---
version: "3.9"

services:
  db:
    container_name: contoso_craft_mysql_db
    restart: always
    image: mysql:8.0
    volumes:
      - contoso_craft:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: contoso_craft
      MYSQL_USER: contosocraftuser
      MYSQL_PASSWORD: contosocraftpassword

  webapp:
    container_name: contoso_craft_webapp
    restart: always
    image: contoso_craft_webapp
    build:
      context: ../
      dockerfile: src/ContosoCraft.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - db
    ports:
      - 5000:5000

  nginx:
    container_name: contoso_craft_proxy
    image: nginx:1.20-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - webapp

volumes:
  contoso_craft:
