---
version: "3.3"

services:
  postgres_db2:
    container_name: contoso_pets-db2
    restart: always
    image: postgres:13.3-alpine
    environment:
      - POSTGRES_DB=contoso_pets
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  app2:
    container_name: contoso_pets-app2
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres_db2
